// Universal Profile Sync Service for seamless extension integration
import { supabase } from '@/integrations/supabase/client';
import { ProfileDatabaseService, UserProfile, ProfileData } from './ProfileDatabaseService';
import { ExtensionService } from './ExtensionService';

export interface SyncedProfile {
  profileId: string;
  profileType: 'student' | 'job_seeker' | 'general';
  profileName: string;
  data: Record<string, any>;
  lastSync: number;
  syncSource: 'webapp' | 'extension' | 'auto';
  version: number;
  autoGenerated?: boolean;
  confidence?: number;
}

export interface SyncStatus {
  isOnline: boolean;
  lastSync: number;
  profileCount: number;
  pendingSyncs: number;
  extensionConnected: boolean;
}

export class UniversalProfileSyncService {
  private static instance: UniversalProfileSyncService;
  private extensionService: ExtensionService;
  private syncInterval: NodeJS.Timeout | null = null;
  private onlineStatus = navigator.onLine;
  private syncListeners: ((status: SyncStatus) => void)[] = [];

  private constructor() {
    this.extensionService = ExtensionService.getInstance();
    this.setupNetworkMonitoring();
    this.startPeriodicSync();
  }

  static getInstance(): UniversalProfileSyncService {
    if (!UniversalProfileSyncService.instance) {
      UniversalProfileSyncService.instance = new UniversalProfileSyncService();
    }
    return UniversalProfileSyncService.instance;
  }

  // Initialize sync service
  async initialize(): Promise<void> {
    console.log('Initializing Universal Profile Sync Service');
    
    // Initial sync from Supabase to extension
    await this.syncProfilesToExtension();
    
    // Set up periodic sync
    this.startPeriodicSync();
  }

  // Sync all user profiles to extension
  async syncProfilesToExtension(): Promise<boolean> {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) {
        console.log('No authenticated user for profile sync');
        return false;
      }

      // Get all user profiles from Supabase
      const profiles = await ProfileDatabaseService.getUserProfiles();
      
      for (const profile of profiles) {
        const profileData = await ProfileDatabaseService.getProfileData(profile.id);
        
        const syncedProfile: SyncedProfile = {
          profileId: profile.id,
          profileType: profile.profile_type as any,
          profileName: profile.profile_name,
          data: this.convertProfileDataToRecord(profileData),
          lastSync: Date.now(),
          syncSource: 'webapp',
          version: 1
        };

        // Send individual profile to extension
        await this.sendProfileToExtension(syncedProfile);
      }

      console.log(`Synced ${profiles.length} profiles to extension`);
      this.notifyListeners();
      return true;

    } catch (error) {
      console.error('Failed to sync profiles to extension:', error);
      return false;
    }
  }

  // Send single profile to extension
  private async sendProfileToExtension(profile: SyncedProfile): Promise<boolean> {
    try {
      const extensionId = this.extensionService.getExtensionId();
      if (!extensionId) {
        console.log('Extension not available for profile sync');
        return false;
      }

      // Send profile data to extension
      const success = await this.extensionService.sendDocumentData({
        extractedData: profile.data,
        documentText: JSON.stringify(profile.data),
        documentType: profile.profileType,
        sessionId: `profile_sync_${profile.profileId}`
      });

      if (success) {
        console.log('Profile synced to extension:', profile.profileId);
      }

      return success;
    } catch (error) {
      console.error('Failed to send profile to extension:', error);
      return false;
    }
  }

  // Convert ProfileData array to Record format
  private convertProfileDataToRecord(profileData: ProfileData[]): Record<string, any> {
    const record: Record<string, any> = {};
    
    profileData.forEach(item => {
      record[item.field_key] = {
        value: item.field_value,
        confidence: item.confidence_score || 100,
        source: item.data_source || 'manual',
        category: item.field_category
      };
    });

    return record;
  }

  // Sync profile data after document processing
  async syncDocumentExtractionResults(
    extractedData: Record<string, any>,
    documentText: string,
    documentType: string,
    shouldCreateProfile = false
  ): Promise<boolean> {
    try {
      // Send to extension immediately
      const extensionSuccess = await this.extensionService.sendExtractionResults(
        extractedData,
        documentText,
        documentType
      );

      // If user wants to create profile, create it in Supabase
      if (shouldCreateProfile) {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const profileType = this.detectProfileTypeFromDocument(documentType, extractedData);
          const profileName = this.generateProfileName(extractedData, documentType);

          const profile = await ProfileDatabaseService.createProfile({
            profile_type: profileType,
            profile_name: profileName
          });

          if (profile) {
            // Save extracted data to profile
            await this.saveExtractedDataToProfile(profile.id, extractedData, documentType);
            
            // Sync the new profile to extension
            await this.syncSingleProfileToExtension(profile.id);
          }
        }
      }

      this.notifyListeners();
      return extensionSuccess;

    } catch (error) {
      console.error('Failed to sync extraction results:', error);
      return false;
    }
  }

  // Sync single profile to extension
  private async syncSingleProfileToExtension(profileId: string): Promise<boolean> {
    try {
      const profileData = await ProfileDatabaseService.getProfileData(profileId);
      const profiles = await ProfileDatabaseService.getUserProfiles();
      const profile = profiles.find(p => p.id === profileId);

      if (!profile) return false;

      const syncedProfile: SyncedProfile = {
        profileId: profile.id,
        profileType: profile.profile_type as any,
        profileName: profile.profile_name,
        data: this.convertProfileDataToRecord(profileData),
        lastSync: Date.now(),
        syncSource: 'webapp',
        version: 1
      };

      return await this.sendProfileToExtension(syncedProfile);
    } catch (error) {
      console.error('Failed to sync single profile:', error);
      return false;
    }
  }

  // Save extracted data to profile
  private async saveExtractedDataToProfile(
    profileId: string,
    extractedData: Record<string, any>,
    documentType: string
  ): Promise<void> {
    for (const [key, value] of Object.entries(extractedData)) {
      if (value && value !== '') {
        const fieldValue = typeof value === 'object' ? value.value || String(value) : String(value);
        const confidence = typeof value === 'object' ? value.confidence || 85 : 85;

        await ProfileDatabaseService.saveProfileData(profileId, [{
          field_key: key,
          field_value: fieldValue,
          confidence_score: confidence,
          data_source: 'document',
          field_category: this.categorizeField(key, documentType)
        }]);
      }
    }
  }

  // Detect profile type from document
  private detectProfileTypeFromDocument(
    documentType: string,
    extractedData: Record<string, any>
  ): 'student' | 'job_seeker' | 'general' {
    const docType = documentType.toLowerCase();
    
    // Student indicators
    if (docType.includes('marksheet') || docType.includes('transcript') || 
        docType.includes('degree') || extractedData.studentId || extractedData.rollNumber) {
      return 'student';
    }
    
    // Job seeker indicators
    if (docType.includes('resume') || docType.includes('cv') || 
        extractedData.experience || extractedData.skills || extractedData.workExperience) {
      return 'job_seeker';
    }
    
    return 'general';
  }

  // Generate profile name
  private generateProfileName(extractedData: Record<string, any>, documentType: string): string {
    const name = extractedData.fullName || extractedData.name || 'Anonymous';
    const type = documentType || 'Document';
    return `${name} (${type})`;
  }

  // Categorize field for better organization
  private categorizeField(fieldKey: string, documentType: string): string {
    const key = fieldKey.toLowerCase();
    
    if (['fullname', 'firstname', 'lastname', 'name'].includes(key)) return 'personal';
    if (['email', 'phone', 'mobile', 'address'].includes(key)) return 'contact';
    if (['education', 'degree', 'qualification', 'school', 'college'].includes(key)) return 'education';
    if (['experience', 'skills', 'job', 'company', 'position'].includes(key)) return 'professional';
    if (['dob', 'dateofbirth', 'gender', 'nationality'].includes(key)) return 'demographics';
    if (key.includes('father') || key.includes('mother') || key.includes('parent')) return 'family';
    
    return 'other';
  }

  // Setup network monitoring
  private setupNetworkMonitoring(): void {
    window.addEventListener('online', () => {
      this.onlineStatus = true;
      console.log('Back online - resuming profile sync');
      this.syncProfilesToExtension();
    });

    window.addEventListener('offline', () => {
      this.onlineStatus = false;
      console.log('Gone offline - profile sync paused');
    });
  }

  // Start periodic sync
  private startPeriodicSync(): void {
    if (this.syncInterval) {
      clearInterval(this.syncInterval);
    }

    // Sync every 5 minutes when online
    this.syncInterval = setInterval(async () => {
      if (this.onlineStatus) {
        await this.syncProfilesToExtension();
      }
    }, 5 * 60 * 1000);
  }

  // Stop sync service
  stopSync(): void {
    if (this.syncInterval) {
      clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
  }

  // Get current sync status
  async getSyncStatus(): Promise<SyncStatus> {
    const { data: { user } } = await supabase.auth.getUser();
    const profileCount = user ? (await ProfileDatabaseService.getUserProfiles()).length : 0;
    
    return {
      isOnline: this.onlineStatus,
      lastSync: Date.now(),
      profileCount,
      pendingSyncs: 0, // Would track failed syncs in a real implementation
      extensionConnected: !!this.extensionService.getExtensionId()
    };
  }

  // Listen for sync status changes
  onSyncStatusChange(callback: (status: SyncStatus) => void): void {
    this.syncListeners.push(callback);
  }

  // Remove sync listener
  removeSyncListener(callback: (status: SyncStatus) => void): void {
    const index = this.syncListeners.indexOf(callback);
    if (index > -1) {
      this.syncListeners.splice(index, 1);
    }
  }

  // Notify all listeners
  private async notifyListeners(): Promise<void> {
    const status = await this.getSyncStatus();
    this.syncListeners.forEach(callback => callback(status));
  }

  // Manual sync trigger
  async triggerManualSync(): Promise<boolean> {
    console.log('Manual sync triggered');
    const success = await this.syncProfilesToExtension();
    this.notifyListeners();
    return success;
  }

  // Check if extension is available and sync if needed
  async ensureExtensionSync(): Promise<boolean> {
    const extensionDetected = await this.extensionService.detectExtension();
    
    if (extensionDetected) {
      return await this.syncProfilesToExtension();
    }
    
    return false;
  }
}

// Export singleton instance
export const universalProfileSync = UniversalProfileSyncService.getInstance();