// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mftzlxhtghtmwvtxgbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdHpseGh0Z2h0bXd2dHhnYmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTU1NzcsImV4cCI6MjA2OTE5MTU3N30.XbASqLF8wL_vno0iWQpSRl8abgziUg2xCettKJ_Cnr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});